# Generated by Django 5.1.2 on 2024-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20),
        ),
    ]
